services:
  app:
    image: $APP_IMAGE
    hostname: "$APP_NAME.$BASE_DOMAIN"
    command: bin/maildev --incoming-user $SMTP_USER --incoming-pass $SMTP_PASSWORD
    networks:
      - dev
    ports:
      - "1025:1025"
    environment:
      - "VIRTUAL_HOST=$APP_NAME.$BASE_DOMAIN"
      - "VIRTUAL_PORT=1080"

networks:
  dev:
    external: true
    name: $NETWORK