#!/bin/bash

umask 0000

cd /var/www

if [ -e "container.env" ]; then
    variables=$(sed "s/^#.*//" "container.env")
    if [ "$variables" != "" ]; then
        export $variables
    fi
fi

if [ ! -e /var/www/storage/ensi ] && [ -e /var/data ]; then
    ln -s /var/data /var/www/storage/ensi
fi

if [ ! -L /var/www/public/storage ]; then
    if [ -e vendor ]; then
        php artisan storage:link
    fi
fi

OCTANE_SHOW_FATAL_ERROR=true php artisan octane:swoole --watch --host=0.0.0.0 --workers=1 --task-workers=1 || sleep 3600