#!/bin/bash

umask 0000

cd /var/www

if [ -e "container.env" ]; then
    variables=$(sed "s/^#.*//" "container.env")
    if [ "$variables" != "" ]; then
        export $variables
    fi
fi

if [ ! -e /var/www/storage/ensi ] && [ -e /var/data ]; then
    ln -s /var/data /var/www/storage/ensi
fi

if [ ! -L /var/www/public/storage ]; then
    if [ -e vendor ]; then
        php artisan storage:link
    fi
fi

if [ "${DEBUG_HOST}" != "" ]; then
    export PHP_IDE_CONFIG=serverName=local
    {
        echo ""
        echo "xdebug.mode=develop,debug"
        echo "xdebug.client_host=${DEBUG_HOST}"
        echo "xdebug.client_port=${DEBUG_PORT}"
        echo "max_execution_time=3600"
        echo ""
    } >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    sed 's/request_terminate_timeout =.*/request_terminate_timeout = 3600s/' -i /usr/local/etc/php-fpm.d/www.conf
fi

php-fpm -R
