services:
  app:
    image: $APP_IMAGE
    hostname: "$APP_NAME.$BASE_DOMAIN"
    networks:
      - dev
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "read_only_allow_delete=false"
      - "ES_JAVA_OPTS=-Xms${JAVA_MEMORY} -Xmx${JAVA_MEMORY}"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "${SVC_PATH}/data:/usr/share/elasticsearch/data:rw"
    ports:
      - "9200:9200"

networks:
  dev:
    external: true
    name: $NETWORK