#!/bin/bash

services=$(elc list --tag=app)

for service in $services; do
    db=$(elc vars $service | sed -En 's/DB_NAME=(.*)/\1/p')
    if [ "$db" != "" ]; then
        printf "Create database %-50s" "${db}"
        elc --svc=database psql -Upostgres -c "create database ${db};" &> /dev/null
        elc --svc=database psql -Upostgres -c "create database ${db}_test;" &> /dev/null
        echo "    [OK]"

        extensions=$(elc vars $service | sed -En 's/DB_EXT=(.*)/\1/p' | tr ',' '\n')
        for extension in $extensions; do
            printf "Create extension ${extension} for %-37s" "${db}"
            elc --svc=database psql -Upostgres ${db} -c "create extension if not exists ${extension};" &> /dev/null
            elc --svc=database psql -Upostgres ${db}_test -c "create extension if not exists ${extension};" &> /dev/null
            echo "    [OK]"
        done
    fi
done
