#!/bin/bash

services=$(elc list --tag=app)

for service in $services; do
    db=$(elc vars $service | sed -En 's/DB_NAME=(.*)/\1/p')
    if [ "$db" != "" ]; then
        printf "Drop database %-50s" "${db}"
        elc --svc=database psql -Upostgres -c "drop database ${db};" &> /dev/null
        elc --svc=database psql -Upostgres -c "drop database ${db}_test;" &> /dev/null
        echo "    [OK]"
    fi
done