#!/bin/bash

BACKUP_DIR=./backup

dbs=$(docker exec ensi-postgres-1 psql -Upostgres -l -q -t | awk '{print $1}' | sed -E '/(template|test|\||postgres)/d')
mkdir -p "${BACKUP_DIR}"

for db in $dbs; do
    printf "Backup database %-25s" "${db}"
    docker exec ensi-postgres-1 pg_dump -Upostgres -C "${db}" > "${BACKUP_DIR}/${db}.sql"
    echo "    [OK]"
done

