#!/bin/bash

mkdir -p home/{.config,.npm,composer,composer_cache}
chmod -R 777 home/{.config,.npm,composer,composer_cache}

mkdir -p services/{database,elastic,kafka}/data
mkdir -p services/es/{data,cache}
chmod -R 777 services/{database,elastic,es,kafka}/data