services:
  app:
    image: $APP_IMAGE
    hostname: "$APP_NAME.$BASE_DOMAIN"
    networks:
      - dev
    environment:
      VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
      VIRTUAL_PORT: "8080"
      SPRING_CONFIG_ADDITIONAL-LOCATION: /config.yml
    volumes:
      - "${SVC_PATH}/kafbat.yaml:/config.yml"

networks:
  dev:
    external: true
    name: $NETWORK